# roles/java/tasks/centos.yml
---
- name: download jdk
  get_url:
    url: http://download.oracle.com/otn-pub/java/jdk/8u91-b14/jdk-8u91-linux-x64.rpm
    dest: /tmp/jdk-8u144-linux-x64.rpm
    force: no
  tags:
    - java
    - installation

- name: install jdk
  yum:
    name: /tmp/jdk-8u91-linux-x64.rpm
    state: present
  become: yes
  tags:
    - java
    - installation
